# Generated by Django 4.2.2 on 2023-06-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
                ('sector_address', models.CharField(max_length=200)),
                ('sector_state', models.CharField(max_length=50)),
                ('sector_district', models.CharField(max_length=50)),
                ('sector_registration_date', models.DateField()),
                ('sector_area_of_operation', models.CharField(max_length=100)),
                ('sector_sector_type', models.CharField(max_length=100)),
            ],
        ),
    ]
