# Generated by Django 4.2.2 on 2023-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_address',
            field=models.CharField(blank=' ', default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_area_of_operation',
            field=models.CharField(blank=' ', default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_district',
            field=models.CharField(blank=' ', default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_name',
            field=models.CharField(blank=' ', default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_registration_date',
            field=models.DateField(blank=' ', default='', null=True),
        ),
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_sector_type',
            field=models.CharField(blank=' ', default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_state',
            field=models.CharField(blank=' ', default='', max_length=50, null=True),
        ),
    ]
