# Generated by Django 4.2.2 on 2023-06-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_cooperativesociety_sector_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_registration_date',
            field=models.DateTimeField(blank=' ', default='', null=True),
        ),
    ]
