# Generated by Django 4.2.2 on 2023-06-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_cooperativesociety_sector_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativesociety',
            name='sector_registration_date',
            field=models.DateField(blank=' ', default='', null=True),
        ),
    ]
